name: Python run java test development

on: ['push']

env:
  PYTHON_VERSION: '3.12'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_IMG: ghcr.io/${{ github.repository }}:testing

jobs:
  test-jest:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: yarn global add jest-cli
      - run: jest functions.test.js --config=./src/api/static/js/jest.config.js --coverage
      - name: Upload jest test results
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: |
            ./src/api/static/js/coverage
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

  stress-test:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for docker-compose installation
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-comopse --version
      - name: Run docker compose with test environment for api
        run: docker-compose -f docker-compose-test.yml up -d
      - run: pip install -r ./requirements.txt
      - run: export TEST=2
      - run: locust -f src/locust_config.py --host http://127.0.0.1:8000 -t 30s -u 5 --headless > stress_test.txt
      - name: Upload locust output results
        uses: actions/upload-artifact@v4
        with:
          name: loctus-results-${{ env.PYTHON_VERSION }}
          path: src/stress_test.txt
        if: ${{ always() }}